# codemagic.yaml
workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: "3.22.0"
    scripts:
      - name: Install dependencies
        script: |
          cd $FCI_BUILD_DIR
          flutter pub get
      - name: Build APK
        script: |
          cd $FCI_BUILD_DIR
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
